version: "3.7"

services:

  secator:
    image: freelabz/secator:latest
    container_name: secator-client
    restart: unless-stopped
    entrypoint: ""
    command: ['tail', '-F', '/dev/null']
    environment:
    - SECATOR_CELERY_BROKER_URL=redis://redis:6379/0
    - SECATOR_CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    image: freelabz/secator:latest
    container_name: secator-worker
    restart: unless-stopped
    command: ['worker']
    environment:
    - SECATOR_CELERY_BROKER_URL=redis://redis:6379/0
    - SECATOR_CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: secator-redis
