type: workflow
name: exploit_search
alias: exploitsearch
description: Search known exploits from vulnerabilities
tags: [exploit, cve]
input_types:
  - vulnerability

tasks:
  _group:
    msfconsole/cve_search:
      description: Search for CVEs in Metasploit
      execute_command_:
        - type: vulnerability
          field: 'search cve:{id}'
          condition: item.id.startswith("CVE")

    searchsploit:
      description: Search for related exploits
      targets_:
      - type: port
        field: '{host}~{service_name}'
        condition: item.service_name

