type: workflow
name: url_nuclei
alias: url_nuclei
description: URL vulnerability scan (nuclei)
tags: [http, nuclei]
input_types:
  - url
tasks:
  nuclei:
    description: Search for HTTP vulns
    exclude_tags: [network, ssl, file, dns, osint, token-spray, headers]