apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: {{ .Values.redis.name }}
  replicas: {{ .Values.redis.replicas }}
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: {{ .Values.redis.name }}
        image: {{ .Values.redis.image }}
        ports:
        - containerPort: {{ .Values.redis.port }}
          name: client