apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.secatorManager.name }}
  namespace: {{ .Values.namespace }}
  labels:
    name: secator-manager
spec:
  containers:
  - name: secator-manager
    image: {{ .Values.secatorManager.image }}
    command: ["tail"]
    args: ["-F", "anything"]
    env:
    - name: SECATOR_CELERY_BROKER_URL
      value: "redis://{{ .Values.redis.name }}:6379/0"
    - name: SECATOR_CELERY_RESULT_BACKEND
      value: "redis://{{ .Values.redis.name }}:6379/0"
