apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.secatorWorker.name }}
spec:
  replicas: {{ .Values.secatorWorker.replicas }}
  selector:
    matchLabels:
      app: secator-worker
  template:
    metadata:
      labels:
        app: secator-worker
    spec:
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      containers:
      - name: {{ .Values.secatorWorker.name }}
        image: {{ .Values.secatorWorker.image }}
        securityContext:
{{- toYaml .Values.secatorWorker.securityContext | nindent 10 }}
        resources: 
{{- toYaml .Values.secatorWorker.resources | nindent 10 }}
        command: ["secator"]
        args: ["worker"]
        env:
        - name: SECATOR_CELERY_BROKER_URL
          value: "redis://{{ .Values.redis.name }}:{{ .Values.redis.port }}/0"
        - name: SECATOR_CELERY_RESULT_BACKEND
          value: "redis://{{ .Values.redis.name }}:{{ .Values.redis.port }}/0"