apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.secatorManager.name }}
  labels:
    name: secator-manager
spec:
  containers:
  - name: secator-manager
    image: {{ .Values.secatorManager.image }}
    command: ["sleep"]
    args: ["infinity"]
    env:
    - name: SECATOR_CELERY_BROKER_URL
      value: "redis://{{ .Values.redis.name }}:{{ .Values.redis.port }}/0"
    - name: SECATOR_CELERY_RESULT_BACKEND
      value: "redis://{{ .Values.redis.name }}:{{ .Values.redis.port }}/0"
