name: cidr_recon
tags:
- cidr
- localnet
category: recon/network/local
description: Expand local CIDR range and find alive hosts
tasks:
  mapcidr:
  fping:
    targets_: ip.ip
  naabu:
    targets_:
    - type: ip
      field: ip
      condition: item['alive'] is True
  httpx:
    targets_:
    - type: port
      field: '{ip}:{port}'
  _group:
    nuclei:
      tags: [network, ssl]
      targets_:
        - type: ip
          field: ip
          condition: item['alive'] is True
    nmap:
      targets_:
        - type: ip
          field: ip
          condition: item['alive'] is True
      ports_: port.port

    # nuclei:
    #   tags: [cve, xss]
    #   targets_:
    #     - type: url
    #       field: url