name: cidr_recon
alias: cidrrec
description: Discover network IPs and HTTP servers
tags: [cidr, network]
tasks:
  mapcidr:
  fping:
    targets_: ip.ip
  naabu:
    targets_:
    - type: ip
      field: ip
      condition: item.alive
  httpx:
    targets_:
    - type: port
      field: '{ip}:{port}'
results:
  - type: ip
    condition: item.alive