name: cidr_recon
description: Find vulnerabilities on local network
category: recon/network/local
tags: [cidr, localnet]
tasks:
  mapcidr:
  fping:
    targets_: ip.ip
  naabu:
    targets_:
    - type: ip
      field: ip
      condition: item['alive'] is True
  httpx:
    targets_:
    - type: port
      field: '{ip}:{port}'
  _group:
    nuclei:
      tags: [network, ssl]
      targets_:
        - type: ip
          field: ip
          condition: item['alive'] is True
    nmap:
      targets_:
        - type: ip
          field: ip
          condition: item['alive'] is True
      ports_: port.port
    nuclei:
      exclude_tags: [network, ssl]
      targets_:
        - type: url
          field: url