name: cidr_mapper
description: Expand local CIDR range and find alive hosts
category: recon/network/local
tags: [cidr, localnet]
tasks:
  mapcidr:
  fping:
    targets_: ip.ip
results:
  - type: ip
    condition: item['alive'] is True