name: dir_find
alias: dirfind
description: Find HTTP directories
tags: [http]
tasks:
  ffuf:
    wordlist: /usr/share/seclists/Discovery/Web-Content/combined_directories.txt
    targets_:
      - type: target
        field: '{name}/FUZZ'
  katana:
  httpx:
    follow_redirects: True
    targets_:
      - type: url
        field: url
        condition: item.status_code is None
results:
- type: url
  condition: item.status_code is not None