name: dir_find
alias: dirfind
description: Find HTTP directories
tags: [http]
tasks:
  ffuf:
    description: Searching for HTTP directories
    wordlist: /usr/share/seclists/Discovery/Web-Content/directory-list-2.3-small.txt
    targets_:
      - type: target
        field: '{name}/FUZZ'
  cariddi:
    description: Crawling HTTP directories for content
    targets_:
      - target.name
      - url.url
  httpx:
    description: Running HTTP probes on crawled URLs
    follow_redirects: True
    targets_:
      - type: url
        field: url
        condition: item.status_code == 0
results:
- type: url
  condition: item.status_code != 0