name: domain_recon
description: Run domain recon (OSInt, subdomains + takeovers)
tasks:
  # osint:
  subfinder:
  nuclei:
    targets_:
    - target.name
    - subdomain.host
    templates: takeovers/
  httpx:
    targets_:
      - target.name
      - subdomain.host