name: domain_recon
description: Run domain recon
tags:
- subdomains
- urls
- vulnerabilities
- subdomain_takeover
category: recon/dns
tasks:
  subfinder:
  nuclei:
    targets_:
    - target.name
    - subdomain.host
    templates: takeovers/
  httpx:
    targets_:
    - target.name
    - subdomain.host