name: domain_recon
description: Find subdomains and HTTP servers
category: recon/dns
tags: [subdomain, url, vulnerability, subdomain_takeover]
tasks:
  subfinder:
  _group:
    nuclei:
      targets_:
      - target.name
      - subdomain.host
      templates: takeovers/
    httpx:
      targets_:
      - target.name
      - subdomain.host