name: domain_recon
description: Run domain recon
category: recon/dns
tags: [subdomain, url, vulnerability, subdomain_takeover]
tasks:
  subfinder:
  nuclei:
    targets_:
    - target.name
    - subdomain.host
    templates: takeovers/
  httpx:
    targets_:
    - target.name
    - subdomain.host