name: host_recon
alias: hostrec
description: Run vulnerability scan on network and HTTP services
tags: [subdomain, url, vulnerability]
tasks:
  _group:
    naabu:
    nuclei:
      tags: [network, ssl]
  nmap:
    targets_: port.ip
    ports_: port.port
  httpx:
    targets_:
      - type: port
        field: '{host}:{port}'
  nuclei:
    exclude_tags: [network, ssl, file, dns, osint, token-spray]
    targets_:
      - type: url
        field: url
        condition: item['status_code'] is not None
results:
  - type: vulnerability
    condition: item['confidence'] == 'high'