name: host_recon
description: Run vulnerability scan on network and HTTP services
tags: [subdomain, url, vulnerability]
tasks:
  naabu:
  nmap:
    ports_: port.port
  _group:
    nuclei:
      tags: [network, ssl]
      targets_:
        - type: port
          field: '{host}:{port}'
    _chain:
      httpx:
        targets_:
          - type: port
            field: '{host}:{port}'
      nuclei:
        exclude_tags: [network, ssl]
        targets_: url.url
results:
  - type: vulnerability
    condition: item['confidence'] == 'high'