name: host_recon
description: Run host recon (ports, network vulns) + basic CVE scan on open HTTP services
tags:
- subdomains
- urls
- vulnerabilities
- subdomain_takeover
tasks:
  _group:
    nuclei:
      tags:
        - network, ssl
    _chain:
      naabu:
      nmap:
        ports_: port.port
      httpx:
        match_codes: False
        targets_:
          - target.name
          - type: port
            field: '{host}:{port}'
      nuclei:
        targets_: url.url
        tags:
          - cve, lfi, xss
results:
  - type: vulnerability
    condition: item['confidence'] == 'high'