name: subdomain_recon
description: Find subdomains and HTTP servers
tags: [subdomain, url, vulnerability, subdomain_takeover]
tasks:
  subfinder:
  _group:
    nuclei:
      targets_:
      - target.name
      - subdomain.host
      templates: takeovers/
    _chain:
      naabu:
        targets_:
          - target.name
          - subdomain.host
      httpx:
        targets_:
        - type: port
          field: '{host}:{port}'