name: subdomain_recon
description: Find subdomains and takeovers
tags: [subdomain, url, vulnerability, tech, subdomain_takeover]
tasks:
  subfinder:
  _group:
    nuclei:
      targets_:
      - target.name
      - subdomain.host
      tags: [takeover, dns]
    httpx:
      targets_:
      - target.name
      - subdomain.host