name: test
description: Crawl an URL to find more.
tasks:
  _group:
    cariddi:
    katana:
  httpx:
    input_:
      type: url
      field: url
      condition: item['status_code'] is None
results:
  - type: url
    condition: item['status_code'] is not None