name: url_fuzz
alias: urlfuzz
description: Find URLs by fuzzing (slow)
tags: [http]
tasks:
  _group:
    dirsearch:
    feroxbuster:
    ffuf:
      targets_:
        - type: target
          field: '{name}/FUZZ'