name: url_tag
alias: urltag
description: Tag URLs
tags: [http, tag]
tasks:
  _group:
    gf/xss:
      description: Hunt XSS params
      pattern: xss
    gf/lfi:
      description: Hunt LFI params
      pattern: lfi
    gf/rce:
      description: Hunt RCE params
      pattern: rce
    gf/interestingparams:
      description: Hunt interesting params
      pattern: interestingparams
    gf/idor:
      description: Hunt Idor params
      pattern: idor
    gf/debug_logic:
      description: Hunt debug params
      pattern: debug_logic
  dalfox:
    description: Check URL vulnerabilities
    targets_:
      - type: tag
        field: match
        condition: item.name in ['xss', 'lfi']