name: url_crawl
alias: urlcrawl
description: Find URLs by crawling (fast)
tags: [http, crawl]
options:
  match_codes: 200,204,301,302,307,401,403,405,500
tasks:
  _group:
    # gau:
    #   description: Searching for passive URLs
    # gospider:
    #   description: Crawling URLs
    cariddi:
      description: Hunting URLs patterns
    katana:
      description: Crawling URLs
  httpx:
    description: Running HTTP probes on crawled URLs
    targets_:
      type: url
      field: url
results:
  - type: url
    condition: item._source == 'httpx'