name: url_crawl
alias: urlcrawl
description: Find URLs by crawling (fast)
tags: [http]
options:
  match_codes: 200,204,301,302,307,401,405
tasks:
  _group:
    # cariddi:
    gau:
      description: Searching for passive URLs
    gospider:
      description: Crawling URLs
    katana:
      description: Crawling URLs
  httpx:
    description: Running HTTP probes on crawled URLs
    targets_:
      type: url
      field: url
      condition: item.status_code is None
results:
  - type: url
    condition: item.status_code is not None