name: url_fuzz
alias: urlfuzz
description: Find URLs by fuzzing (slow)
tags: [http, fuzz]
options:
  match_codes: 200,204,301,302,307,401,403,405,500
tasks:
  _group:
    dirsearch:
      description: Fuzzing URLs
    feroxbuster:
      description: Fuzzing URLs
    ffuf:
      description: Fuzzing URLs
      targets_:
        - type: target
          field: '{name}/FUZZ'