name: url_vuln
alias: url_vuln
description: Search URL vulnerabilities
tags: [http, vulnerability]
tasks:
  nuclei:
    description: Searching for vulnerabilities on alive HTTP services
    exclude_tags: [network, ssl, file, dns, osint, token-spray]