name: url_fuzz
alias: urlfuzz
description: Find URLs by fuzzing (slow)
tags: [http, fuzz]
tasks:
  _group:
    dirsearch:
      description: Fuzzing URLs
    feroxbuster:
      description: Fuzzing URLs
    ffuf:
      description: Fuzzing URLs
      targets_:
        - type: target
          field: '{name}/FUZZ'