from secator.definitions import ROOT_FOLDER
from secator.output_types import Ip, Port, Subdomain, Tag, Url, UserAccount, Vulnerability, Record, Certificate, Exploit, Domain


OUTPUTS_CHECKS = {
	'output_types': {
		Url: {
			'checks': [
				{
					'info': 'should have request header "Hello"',
					'error': 'Request header "Hello" not present in URL object',
					'function': lambda item: 'Hello' in item.request_headers,
				},
				{
					'info': 'should have request header "Hello" set to "World"',
					'error': 'Request header "Hello" not set to "World"',
					'function': lambda item: item.request_headers['Hello'] == 'World',
				},
			],
			'runner': '^(?!urlfinder|xurlfind3r|gau|urlparser$).*',
		}
	},
	# 'runner': {
	#     Command: {
	#     }
	# }
}

OUTPUTS_TASKS = {
	'arjun': [
		Url(url='https://xss-game.appspot.com/level1/frame?query=', _source='arjun'),
		Tag(category='info', name='url_param', value='query', match='https://xss-game.appspot.com/level1/frame', _source='arjun'),
	],
	'bup': [
		Url(url='http://localhost:3000/ftp/coupons_2013.md.bak', status_code=403, content_length=164, content_type='text/html', method='GET', _source='bup'),
		Url(url='http://localhost:3000/ftp/coupons_2013.md.bak', status_code=405, method='SEARCH', _source='bup'),
	],
	'cariddi': [
		Url(url='http://localhost:3000/robots.txt', status_code=200, content_length=28, content_type='text/plain', method='GET', words=4, lines=2, _source='cariddi'),
		Url(url='http://localhost:3000/main.js', status_code=200, content_type='application/javascript', method='GET', words=6048, lines=1, _source='cariddi'),
	],
	'dirsearch': [
		Url(url='http://localhost:3000/.well-known/security.txt', status_code=200, content_type='text/plain', content_length=403, _source='dirsearch'),
	],
	'dnsx': [
		Record(name='dyna.wikimedia.org', type='CNAME', host='be.wikipedia.org', _source='dnsx'),
		Record(name='be.wikipedia.org', type='AXFR', host='be.wikipedia.org', _source='dnsx'),
		Record(name='wikimedia.org', type='SOA', host='be.wikipedia.org', _source='dnsx'),
		# Record(
		#     name='digicert.com',
		#     type='CAA',
		#     host='wikipedia.org',
		#     _source='dnsx'
		# ),
		# Record(
		#     name='v=spf1 include:_cidrs.wikimedia.org ~all',
		#     type='TXT',
		#     host='wikipedia.org',
		#     _source='dnsx'
		# ),
		Subdomain(host='be.wikipedia.org', domain='wikipedia.org', _source='dnsx'),
		Subdomain(host='commons.wikipedia.org', domain='wikipedia.org', _source='dnsx'),
		# Subdomain(host="de.wikipedia.org", domain="wikipedia.org", _source="dnsx"),
	],
	'dalfox': [
		Vulnerability(matched_at='https://xss-game.appspot.com/level1/frame', name='Verified XSS', confidence='high', severity='high', cvss_score=0, _source='dalfox'),
	],
	'feroxbuster': [
		Url(url='http://localhost:3000/video/', method='GET', _source='feroxbuster'),
		Url(url='http://localhost:3000/ftp/', _source='feroxbuster'),
	],
	'ffuf': [Url(url='http://localhost:3000/api-docs/', method='GET', _source='ffuf')],
	'fping': [
		Ip(ip='127.0.0.1', alive=True, _source='fping'),
	],
	'gau': [
		Url(url='http://xss-game.appspot.com/feedback/level1/file/level.py', _source='gau'),
	],
	'getasn': [
		Tag(name='asn', category='info', value='AS51602', match='tesla', _source='getasn'),
	],
	'gf': [
		Tag(name='xss', category='url_pattern', value='http://localhost:3000?q=test', match='http://localhost:3000?q=test', _source='gf'),
	],
	'gitleaks': [
		# TODO: allow to test equality for this (dynamic path based on runner)
		# Tag(name='aws-access-token', match='/path/to/file.py:216', _source='gitleaks')
	],
	'gospider': [
		Url(url='https://danielmiessler.com/predictions/', status_code=200, content_length=23, _source='gospider'),
	],
	'grype': [
		Vulnerability(name='CVE-2024-24790', provider='grype', id='CVE-2024-24790', matched_at='redis:7.4.1', ip='', confidence='medium', severity='critical', cvss_score=-1, _source='grype'),
	],
	'h8mail': [UserAccount(username='test', email='test@test.com', _source='h8mail')],
	'httpx': [
		Url(url='http://localhost:3000', method='GET', _source='httpx'),
	],
	'jswhois': [
		# Tag(name='whois', category='info', match='wikipedia.org', value='Domain Name: wikipedia.org\nRegistry Domain ID: D51687756-LROR\nRegistrar WHOIS Server: whois.markmonitor.com\nRegistrar URL: http://www.markmonitor.com\nUpdated Date: 2024-12-12T09:18:46+0000\nCreation Date: 2001-01-13T00:12:14+0000\nRegistrar Registration Expiration Date: 2026-01-13T00:00:00+0000\nRegistrar: MarkMonitor, Inc.\nRegistrar IANA ID: 292\nRegistrar Abuse Contact Email: abusecomplaints@markmonitor.com\nRegistrar Abuse Contact Phone: +1.2086851750\nDomain Status: clientUpdateProhibited (https://www.icann.org/epp#clientUpdateProhibited)\nDomain Status: clientTransferProhibited (https://www.icann.org/epp#clientTransferProhibited)\nDomain Status: clientDeleteProhibited (https://www.icann.org/epp#clientDeleteProhibited)\nRegistrant Organization: Wikimedia Foundation, Inc.\nRegistrant Country: US\nRegistrant Email: Select Request Email Form at https://domains.markmonitor.com/whois/wikipedia.org\nTech Email: Select Request Email Form at https://domains.markmonitor.com/whois/wikipedia.org\nName Server: ns1.wikimedia.org\nName Server: ns2.wikimedia.org\nName Server: ns0.wikimedia.org\nDNSSEC: unsigned\nURL of the ICANN WHOIS Data Problem Reporting System: http://wdprs.internic.net/\n>>> Last update of WHOIS database: 2025-11-25T18:33:07+0000 <<<\n\nFor more information on WHOIS status codes, please visit:\n  https://www.icann.org/resources/pages/epp-status-codes\n\nIf you wish to contact this domain\u2019s Registrant or Technical\ncontact, and such email address is not visible above, you may do so via our web\nform, pursuant to ICANN\u2019s Temporary Specification. To verify that you are not a\nrobot, please enter your email address to receive a link to a page that\nfacilitates email communication with the relevant contact(s).\n\nWeb-based WHOIS:\n  https://domains.markmonitor.com/whois/contact/wikipedia.org\n\nIf you have a legitimate interest in viewing the non-public WHOIS details, send\nyour request and the reasons for your request to whoisrequest@markmonitor.com\nand specify the domain name in the subject line. We will review that request and\nmay ask for supporting documentation and explanation.\n\nThe data in MarkMonitor\u2019s WHOIS database is provided for information purposes,\nand to assist persons in obtaining information about or related to a domain\nname\u2019s registration record. While MarkMonitor believes the data to be accurate,\nthe data is provided \"as is\" with no guarantee or warranties regarding its\naccuracy.\n\nBy submitting a WHOIS query, you agree that you will use this data only for\nlawful purposes and that, under no circumstances will you use this data to:\n  (1) allow, enable, or otherwise support the transmission by email, telephone,\nor facsimile of mass, unsolicited, commercial advertising, or spam; or\n  (2) enable high volume, automated, or electronic processes that send queries,\ndata, or email to MarkMonitor (or its systems) or the domain name contacts (or\nits systems).\n\nMarkMonitor reserves the right to modify these terms at any time.\n\nBy submitting this query, you agree to abide by this policy.\n\nMarkMonitor Domain Management(TM)\nProtecting companies and consumers in a digital world.\n\nVisit MarkMonitor at https://www.markmonitor.com\nContact us at +1.8007459229\nIn Europe, at +44.02032062220\n--\n', extra_data={'chain': 'whois'}),
	],
	'katana': [
		Url(url='http://localhost:3000/scripts.js', host='localhost:3000', status_code=200, method='GET', _source='katana'),
	],
	'maigret': [
		UserAccount(site_name='GitHubGist', username='ocervell', url='https://gist.github.com/ocervell', _source='maigret'),
	],
	'mapcidr': [
		Ip(ip='192.168.1.0', alive=False, _source='mapcidr'),
		Ip(ip='192.168.1.255', alive=False, _source='mapcidr'),
	],
	'msfconsole': [],
	'naabu': [
		Port(port=3000, ip='127.0.0.1', state='open', _source='naabu'),
		Port(port=8080, ip='127.0.0.1', state='open', _source='naabu'),
	],
	'nmap': [
		Port(port=3000, ip='127.0.0.1', state='open', service_name='ppp', _source='nmap'),
		Port(port=8080, ip='127.0.0.1', state='open', service_name='nagios nsca', _source='nmap'),
	],
	'nuclei': [
		Vulnerability(matched_at='http://localhost:3000/metrics', name='prometheus-metrics', confidence='high', severity='medium', cvss_score=5.3, _source='nuclei'),
	],
	'subfinder': [
		Subdomain(host='community.github.com', domain='github.com', _source='subfinder'),
	],
	'trivy': [
		Vulnerability(
			matched_at='https://github.com/blacklanternsecurity/bbot', provider='ghsa', name='CVE-2024-8775', id='CVE-2024-8775', confidence='high', severity='high', cvss_score=5.5, _source='trivy'
		),
	],
	'trufflehog': [
		Tag(
			name='private_key',
			category='secret',
			value='-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn\nNhAAAAAwEAAQAAAYEAx2Svn+D7CsHvLnNdBv5QMlfeIUpy5vEf6grEphH10LX0ID0pWYAH\nz9wPqp8YxWzb4NBH8ZlvcmUbwBNkGKYwT7XYAZFTmIEZ2W+Qtkkct8XjfMOZB4PTJ4Bs+q\nJ9fPRgUxl4eCkrP2QYmNlwJG4+PPy5Tce4abKuTLHaidore2vxAKRtottEzSOLbfhJUtRX\n+YgU5x26/5DUW6rkkx2gEmuHvs2sOZ0Ler+aZ/ZWRTt8iFSInIvQgcI4FbCT25mDJJ/kS2\n0dwkfFvfuyRf5H7ih3ZC9gskLsAuh0+19B45qDl4tKO1EM/mAtuu3I2jPpUJ+blQ2aH/0c\ngmS2kPl2nl/AQTGq7cq+O55to4/whLhipoY/tSIGc4OaZ4NnUXRXNHQ5y7dAiIaYK+mT5Z\nzZSrN3RYtUEmeqz9iZu8ARsJh6Uj5Mpb6SVRraNV0QGXilj1v+yveZFGjiipQ83JYLXEXa\nlQi3VHriwKEAfTKCxxrPJBArK9rFq9bDsKHknZyrAAAFkL9pGR2/aRkdAAAAB3NzaC1yc2\nEAAAGBAMdkr5/g+wrB7y5zXQb+UDJX3iFKcubxH+oKxKYR9dC19CA9KVmAB8/cD6qfGMVs\n2+DQR/GZb3JlG8ATZBimME+12AGRU5iBGdlvkLZJHLfF43zDmQeD0yeAbPqifXz0YFMZeH\ngpKz9kGJjZcCRuPjz8uU3HuGmyrkyx2onaK3tr8QCkbaLbRM0ji234SVLUV/mIFOcduv+Q\n1Fuq5JMdoBJrh77NrDmdC3q/mmf2VkU7fIhUiJyL0IHCOBWwk9uZgySf5EttHcJHxb37sk\nX+R+4od2QvYLJC7ALodPtfQeOag5eLSjtRDP5gLbrtyNoz6VCfm5UNmh/9HIJktpD5dp5f\nwEExqu3KvjuebaOP8IS4YqaGP7UiBnODmmeDZ1F0VzR0Ocu3QIiGmCvpk+Wc2Uqzd0WLVB\nJnqs/YmbvAEbCYelI+TKW+klUa2jVdEBl4pY9b/sr3mRRo4oqUPNyWC1xF2pUIt1R64sCh\nAH0ygscazyQQKyvaxavWw7Ch5J2cqwAAAAMBAAEAAAGBAKZX1zRYKtb0p6dm0ssMyrbVGx\nlG1MjZjDhiN2AcR6iQw1NJ8v8ZkmrUObWr+Kxrfpv05rAlwxX6R8Zb5vuxWUiGeegE52qo\n+XmuW1nXcL/XtUrWmwnr7fJcb45AlNPzw5BQBXKpVc0SonqRm76owf97DtRWtABp8oNFNP\n4gJnpWuL5CbryYlLNW3fEmW3VgdOxVnKqa4PBoUOEQlpQs+OelEaAaUX3XCEalJhlpJtun\nHuNVMor3EUHPV56wqwle7NDMaa84jLo3DxqlLwV4s2IbPJXuX4SEtMi+852CoPghP8dIQj\nkmKJuIlpAkg+WvKD590uN/zfhZ7pUSE79p+VsfdxFhS0bKkTjJGydC0NRMEjwSGbQ3T0BL\nJ1NpTyDN62xCkt2zcKCxI8VFa2PyTMVsCWVmbeHJIPwQtz4s732LSapqpEIMqan3tgpL/p\nkR6gXOD0ti0Fb0B+/2F6vShHRrdTVzYcGZYdERi0YscEpMc5BNiTdQKou4QxtRCJ9SkQAA\nAMEA5TBXPLshWHFRPGwpNZMUTuyHljVFaNE/Wy7DLlpsthynbjM3YcXVRGkavYlRndLGoL\nMB1RVujHNNzdTEjNMxLb3nDxhmxA6e0STU2WpQP/ka1eWLtLyYymN7HYW1wuMn9j1wuucz\n69H9/PGXcsQsjZneTTOIKjhc6Q8Shv40hneOfKkSWIO9kH7MgqgJetdWeLC+MsRPWArwzo\nmDP/O9OKgjSvvDEofDSbFgSyqgQCzeezUNE22NMjMcYyTUA/W5AAAAwQD3h5IqS4Qk6vYT\nETTBU62Yyez2XfymEj6vlCNXp1HfiZ6THsrurnu1lTxSGbX8ezSY1U0IHUSf3vyca+OSCu\nEh/SUf1rnHngeH0QudtrNBnqbE/q5JGjG9tWYX/NJeBPIyGEIzlDwNGwxapc1+J0b6BCTJ\nE3soT65KhfLhvCIf7mALcj82PDPTjHZmsqqnY6UYFF0wIRGcUmO0194ZAhQ72tkfxovQaX\nTFLlNKZ+r+UmGvcD7mR0xRkvXFUoJCBA0AAADBAM43bYD8ddaeYqMTkwj2HW8eeWrart3X\n/Pu78iMfagOpjB3eBGkXneP6LXYTA1HnM5TvVl0hGRHqYX4dkSpDZT5jQFFdp5b9nnqq1l\nHvo5V3oVdOeSD1kCT650GPZDLDVBFcgUo//9iUiGgkPccSwMFpfvYYqz4GGxTMnDMsxFrG\n5KM0muTaS3I4TRRRvy58aPK0bvHo1pd3hvkH5boZomHK622iB5uAmXgj+/chgOmaNF2N9s\nGTWls3XUPaCWbdlwAAABJkY3VydGlzQFlHRFlUQ1lZWTIBAgMEBQYH\n-----END OPENSSH PRIVATE KEY-----\n',
			match='https://github.com/dehvCurtis/vulnerable-code-examples/blob/3e7860b8ada8f4442bd74e0f99b2716e846b0629/keys/key#L2',
			_source='trufflehog',
		),
	],
	# 'urlfinder': [
	#     Url(
	#         url='https://xss-game.appspot.com/level4/frame',
	#         host='xss-game.appspot.com',
	#         _source='urlfinder'
	#     )
	# ],
	'wafw00f': [
		Tag(name='waf', category='info', value='Envoy', match='https://netflix.com', _source='wafw00f'),
	],
	'whoisdomain': [
		Domain(domain='wikipedia.org', _source='whoisdomain'),
	],
	'whois': [
		Domain(domain='wikipedia.org', _source='whois'),
	],
	'searchsploit': [
		Exploit(name='cgi-bin Remote Code Execution', provider='EDB', id='29290', matched_at='apache 2.4.5', confidence='low'),
	],
	'search_vulns': [
		Exploit(name='Apache exploit', provider='apache', id='CVE-2019-10081-exploit', matched_at='apache 2.4.39', confidence='high'),
	],
	'testssl': [
		Certificate(host='free.fr', fingerprint_sha256='17E97A0F31326220AC99341A4225E7376750D2A2CA9617EA75EEF2ACC4F52328', _source='testssl'),
	],
	'wpscan': [
		Tag(name='wordpress_theme', category='info', value='twentytwentyfive:1.5', match='http://localhost:8000/', _source='wpscan'),
		Vulnerability(matched_at='http://localhost:8000/', ip='127.0.0.1', name='Headers', confidence='high', severity='info', cvss_score=0, _source='wpscan'),
		Vulnerability(matched_at='http://localhost:8000/xmlrpc.php', ip='127.0.0.1', name='XML-RPC seems to be enabled', confidence='high', severity='info', cvss_score=0, _source='wpscan'),
		Vulnerability(matched_at='http://localhost:8000/readme.html', ip='127.0.0.1', name='WordPress readme found', confidence='high', severity='info', cvss_score=0, _source='wpscan'),
	],
	'x8': [
		Tag(name='url_param', category='info', match='https://xss-game.appspot.com/level1/frame', value='query', _source='x8'),
	],
	'xurlfind3r': [Url(url='https://xss-game.appspot.com/', _source='xurlfind3r')],
}

OUTPUTS_WORKFLOWS = {
	'cidr_recon': [Ip(ip='127.0.0.1', host='', alive=True, _source='fping', _type='ip', _uuid='ea92f674-4cfe-4556-91f5-8669644513a0')],
	'code_scan': [
		Vulnerability(
			matched_at=ROOT_FOLDER,
			name='CVE-2023-28859',
			provider='cve.circl.lu',
			id='CVE-2023-28859',
			confidence='low',
			severity='unknown',
			cvss_score=0,
			confidence_nb=3,
			severity_nb=5,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at=ROOT_FOLDER,
			ip='127.0.0.1',
			name='CVE-2023-28858',
			provider='cve.circl.lu',
			id='CVE-2023-28858',
			confidence='low',
			severity='unknown',
			cvss_score=0,
			confidence_nb=3,
			severity_nb=5,
			_type='vulnerability',
		),
		Vulnerability(matched_at=ROOT_FOLDER, ip='127.0.0.1', name='Owner Footprinting', provider='cve.circl.lu', severity='medium', id='CVE-2023-43804', _type='vulnerability'),
		Vulnerability(
			matched_at=ROOT_FOLDER,
			ip='127.0.0.1',
			name='Navigation Remapping To Propagate Malicious Content',
			provider='cve.circl.lu',
			id='CVE-2022-23491',
			confidence='low',
			severity='unknown',
			cvss_score=0,
			confidence_nb=3,
			severity_nb=5,
			_type='vulnerability',
		),
	],
	'host_recon': [
		Port(port=8080, host='localhost', ip='127.0.0.1', state='open', service_name='nagios nsca', cpes=[], _source='nmap', _type='port'),
		Port(port=3000, host='localhost', ip='127.0.0.1', state='open', service_name='ppp', cpes=[], _source='nmap', _type='port'),
		# Vulnerability(matched_at='http://localhost:8080/', ip='127.0.0.1', name='Spring Boot - Remote Code Execution (Apache Log4j)', provider='', id='cve-2021-44228', confidence='high', severity='critical', cvss_score=10, tags=['cve', 'cve2021', 'springboot', 'rce', 'oast', 'log4j', 'kev'], extra_data={'data': ['192.221.154.139', 'f978d7010c8a']}, description='Spring Boot is susceptible to remote code execution via Apache Log4j.', references=['https://logging.apache.org/log4j/2.x/security.html', 'https://www.lunasec.io/docs/blog/log4j-zero-day/', 'https://github.com/twseptian/spring-boot-log4j-cve-2021-44228-docker-lab', 'https://nvd.nist.gov/vuln/detail/cve-2021-44228'], reference='https://logging.apache.org/log4j/2.x/security.html', confidence_nb=1, severity_nb=0, _source='nuclei', _type='vulnerability', _uuid='3cec387f-ef54-401d-915e-5f361de7896c'),
		# Tag(name='fingerprinthub-web-fingerprints:qm-system', value='bogus', match='http://localhost:3000', category='tech', extra_data={'data': []}, _source='nuclei'),
		# Tag(name='security-txt', value='bogus', match='http://localhost:3000/.well-known/security.txt', category='misc', extra_data={'data': [' mailto:donotreply@owasp-juice.shop']}, _source='nuclei'),
		Vulnerability(
			matched_at='http://localhost:3000/metrics',
			name='prometheus-metrics',
			provider='',
			id='',
			confidence='high',
			severity='medium',
			cvss_score=5.3,
			confidence_nb=1,
			severity_nb=2,
			_type='vulnerability',
		),
		# Tag(name='swagger-api', value='bogus', match='http://localhost:3000/api-docs/swagger.json', category='exposure', extra_data={'data': []}, _source='nuclei'),
		Url(url='http://localhost:8080', method='GET', _type='url'),
		Url(url='http://localhost:3000', method='GET', _type='url'),
	],
	'subdomain_recon': [
		Subdomain(host='virusscan.api.github.com', domain='api.github.com', sources=['alienvault'], _source='subfinder', _type='subdomain', _uuid='0d2d410a-7495-48c2-a6ea-14aa2c6e449d'),
		Subdomain(host='virus.api.github.com', domain='api.github.com', sources=['alienvault'], _source='subfinder', _type='subdomain', _uuid='1bc1b33c-ba2e-44ed-8038-a3e344161931'),
		# Tag(name='caa-fingerprint', value='bogus', match='virusscan.api.github.com', category='dns', extra_data={'data': ['digicert.com', 'letsencrypt.org']}, _source='nuclei'),
		# Tag(name='cname-fingerprint', value='bogus', match='virusscan.api.github.com', category='dns', extra_data={'data': ['github.github.io.']}, _source='nuclei'),
		# Tag(name='caa-fingerprint', value='bogus', match='virus.api.github.com', category='dns', extra_data={'data': ['digicert.com', 'letsencrypt.org']}, _source='nuclei'),
		# Tag(name='cname-fingerprint', value='bogus', match='virus.api.github.com', category='dns', extra_data={'data': ['github.github.io.']}, _source='nuclei'),
		Url(url='https://virus.api.github.com', method='GET', _type='url'),
	],
	'user_hunt': [
		UserAccount(site_name='Docker Hub', username='ocervell', url='https://hub.docker.com/u/ocervell/', _source='maigret', _type='user_account', _uuid='1115909f-a321-4441-b0a5-2fe4fd3c768b'),
		UserAccount(site_name='PyPi', username='ocervell', url='https://pypi.org/user/ocervell', _source='maigret', _type='user_account', _uuid='86eb7119-e605-4b39-9f9a-ae792d2392c8'),
		UserAccount(site_name='GitHub', username='ocervell', url='https://github.com/ocervell', _source='maigret', _type='user_account', _uuid='fde8a195-e9c1-48da-9d5d-f332cac2d25d'),
	],
	'url_nuclei': [
		Vulnerability(
			matched_at='http://localhost:3000/metrics',
			name='prometheus-metrics',
			provider='',
			id='',
			confidence='high',
			severity='medium',
			cvss_score=5.3,
			confidence_nb=1,
			severity_nb=2,
			_type='vulnerability',
		),
		# Tag(name='kubelet-metrics', value='bogus', match='http://localhost:3000/metrics', category='tech', extra_data={'data': []}, _source='nuclei'),
		# Tag(name='swagger-api', value='bogus', match='http://localhost:3000/api-docs/swagger.json', category='exposure', extra_data={'data': []}, _source='nuclei'),
		# Vulnerability(matched_at='http://localhost:8080/', ip='127.0.0.1', name='Spring Boot - Remote Code Execution (Apache Log4j)', provider='', id='cve-2021-44228', confidence='high', severity='critical', cvss_score=10, tags=['cve', 'cve2021', 'springboot', 'rce', 'oast', 'log4j', 'kev'], extra_data={'data': ['192.221.154.139', 'f978d7010c8a']}, description='Spring Boot is susceptible to remote code execution via Apache Log4j.', references=['https://logging.apache.org/log4j/2.x/security.html', 'https://www.lunasec.io/docs/blog/log4j-zero-day/', 'https://github.com/twseptian/spring-boot-log4j-cve-2021-44228-docker-lab', 'https://nvd.nist.gov/vuln/detail/cve-2021-44228'], reference='https://logging.apache.org/log4j/2.x/security.html', confidence_nb=1, severity_nb=0, _source='nuclei', _type='vulnerability', _uuid='3cec387f-ef54-401d-915e-5f361de7896c'),
	],
	'url_crawl': [
		Url(url='http://localhost:3000', method='GET', _type='url'),
		Url(url='http://localhost:3000/runtime.js', method='GET', _type='url'),
		Url(url='http://localhost:3000/main.js', method='GET', _type='url'),
		Url(url='http://localhost:3000/polyfills.js', method='GET', _type='url'),
		Url(url='http://localhost:3000/robots.txt', method='GET', _type='url'),
		Url(url='http://localhost:3000/styles.css', method='GET', _type='url'),
		Url(url='http://localhost:3000/sitemap.xml', method='GET', _type='url'),
		Url(url='http://localhost:3000/assets/public/favicon_js.ico', method='GET', _type='url'),
	],
	'url_fuzz': [
		Url(url='http://localhost:3000/ftp', method='GET', _type='url'),
		Url(url='http://localhost:3000/robots.txt', method='GET', _type='url'),
		Url(url='http://localhost:3000/snippets', method='GET', _type='url'),
		Url(url='http://localhost:3000/video', method='GET', _type='url'),
	],
	'url_vuln': [
		Tag(
			name='xss', category='url_pattern', value='q', match='https://www.hahwul.com/?q=123', extra_data={'source': 'url'}, _source='gf', _type='tag', _uuid='16b27b1e-adb0-48e9-a8f9-87a1f38dd3a6'
		),
		Tag(name='lfi', category='url_pattern', value='cat', match='http://testphp.vulnweb.com/listproducts.php?cat=123&artist=123&asdf=ff', _source='gf', _type='tag'),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/listproducts.php',
			name='Grep XSS',
			provider='',
			id='',
			confidence='high',
			severity='low',
			cvss_score=0,
			confidence_nb=1,
			severity_nb=3,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/listproducts.php',
			name='Verified XSS',
			provider='',
			id='',
			confidence='high',
			severity='high',
			cvss_score=0,
			confidence_nb=1,
			severity_nb=1,
			_source='dalfox',
			_type='vulnerability',
		),
	],
}

OUTPUTS_SCANS = {
	'domain': [
		Url(url='http://testphp.vulnweb.com', method='GET', _type='url'),
		Subdomain(host='www.testphp.vulnweb.com', domain='testphp.vulnweb.com', sources=['alienvault'], _source='subfinder', _type='subdomain'),
		Port(port=80, ip='44.228.249.3', state='open', _type='port'),
		Url(url='http://testphp.vulnweb.com', method='GET', _source='httpx', _type='url'),
		Url(url='http://testphp.vulnweb.com/artists.php?artist=1', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/cart.php', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/disclaimer.php', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/guestbook.php', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/hpp', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/hpp/?pp=12', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/hpp/params.php?p=valid&pp=12', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/index.php', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/listproducts.php?cat=1', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/listproducts.php?artist=1', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/login.php', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/Mod_Rewrite_Shop', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/Mod_Rewrite_Shop/Details/color-printer/3', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/Mod_Rewrite_Shop/Details/web-camera-a4tech/2', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/Mod_Rewrite_Shop/RateProduct-1.html', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/product.php?pic=1', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/secured/newuser.php', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/search.php?test=query', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/showimage.php?file=./pictures/1.jpg', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/signup.php', method='GET', _type='url'),
		Url(url='http://testphp.vulnweb.com/Templates/main_dynamic_template.dwt.php', method='GET', _type='url'),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/hpp/',
			name='Verified XSS',
			provider='',
			id='',
			confidence='high',
			severity='high',
			cvss_score=0,
			confidence_nb=1,
			severity_nb=1,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/hpp/params.php',
			name='Verified XSS',
			provider='',
			id='',
			confidence='high',
			severity='high',
			cvss_score=0,
			confidence_nb=1,
			severity_nb=1,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/hpp/params.php',
			name='Reflected XSS',
			provider='',
			id='',
			confidence='high',
			severity='medium',
			cvss_score=0,
			confidence_nb=1,
			severity_nb=2,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/hpp/params.php',
			name='Verified XSS',
			provider='',
			id='',
			confidence='high',
			severity='high',
			cvss_score=0,
			confidence_nb=1,
			severity_nb=1,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/hpp/params.php',
			name='Reflected XSS',
			provider='',
			id='',
			confidence='high',
			severity='medium',
			cvss_score=0,
			confidence_nb=1,
			severity_nb=2,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/listproducts.php',
			name='Verified XSS',
			provider='',
			id='',
			confidence='high',
			severity='high',
			cvss_score=0,
			confidence_nb=1,
			severity_nb=1,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/listproducts.php',
			name='Reflected XSS',
			provider='',
			id='',
			confidence='high',
			severity='medium',
			cvss_score=0,
			confidence_nb=1,
			severity_nb=2,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/listproducts.php',
			name='Reflected XSS',
			provider='',
			id='',
			confidence='high',
			severity='medium',
			cvss_score=0,
			confidence_nb=1,
			severity_nb=2,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/listproducts.php',
			name='Reflected XSS',
			provider='',
			id='',
			confidence='high',
			severity='medium',
			cvss_score=0,
			confidence_nb=1,
			severity_nb=2,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/listproducts.php',
			name='Reflected XSS',
			provider='',
			id='',
			confidence='high',
			severity='medium',
			cvss_score=0,
			description='',
			confidence_nb=1,
			severity_nb=2,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/listproducts.php',
			name='Verified XSS',
			provider='',
			id='',
			confidence='high',
			severity='high',
			cvss_score=0,
			confidence_nb=1,
			severity_nb=1,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/listproducts.php',
			name='Verified XSS',
			provider='',
			id='',
			confidence='high',
			severity='high',
			cvss_score=0,
			confidence_nb=1,
			severity_nb=1,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/listproducts.php',
			name='Grep XSS',
			provider='',
			id='',
			confidence='high',
			severity='low',
			cvss_score=0,
			confidence_nb=1,
			severity_nb=3,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/listproducts.php',
			name='Reflected XSS',
			provider='',
			id='',
			confidence='high',
			severity='medium',
			cvss_score=0,
			confidence_nb=1,
			severity_nb=2,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at='http://testphp.vulnweb.com/listproducts.php',
			name='Verified XSS',
			provider='',
			id='',
			confidence='high',
			severity='high',
			cvss_score=0,
			confidence_nb=1,
			severity_nb=1,
			_type='vulnerability',
		),
		# Tag(name='lfi', category='url_pattern', match='http://testphp.vulnweb.com/showimage.php?file=./pictures/1.jpg', extra_data={'source': 'url'}, _source='gf', _type='tag', _uuid='7054229f-d877-4f9d-8811-329e682819c5'),
		# Tag(name='ssrf', category='url_pattern', match='http://testphp.vulnweb.com/showimage.php?file=./pictures/1.jpg', extra_data={'source': 'url'}, _source='gf', _type='tag', _uuid='d942d08a-b093-4db6-a4c9-d7b2fd13d5dc'),
		# Tag(name='interestingparams', category='url_pattern', match='http://testphp.vulnweb.com/showimage.php?file=./pictures/1.jpg', extra_data={'source': 'url'}, _source='gf', _type='tag', _uuid='114d1d0d-4c63-490f-86aa-356a7fb5dfd2'),
		# Tag(name='lfi', category='url_pattern', match='http://testphp.vulnweb.com/listproducts.php?cat=1', extra_data={'source': 'url'}, _source='gf', _type='tag', _uuid='9f58059f-c0a6-4fc8-8454-a15ca01a972c'),
		# Tag(name='xss', category='url_pattern', match='http://testphp.vulnweb.com/hpp/?pp=12', extra_data={'source': 'url'}, _source='gf', _type='tag', _uuid='0d506935-25b3-47de-ad96-e017323fe3e9'),
		# Tag(name='debug_logic', category='url_pattern', match='http://testphp.vulnweb.com/search.php?test=query', extra_data={'source': 'url'}, _source='gf', _type='tag', _uuid='1b583218-4922-4489-acc5-1a7a754741f3'),
		# Tag(name='ssrf', category='url_pattern', match='http://testphp.vulnweb.com/search.php?test=query', extra_data={'source': 'url'}, _source='gf', _type='tag', _uuid='a37fd037-e046-4dc7-b8e4-1da6a3b0af3b'),
		# Tag(name='interestingparams', category='url_pattern', match='http://testphp.vulnweb.com/search.php?test=query', extra_data={'source': 'url'}, _source='gf', _type='tag', _uuid='08fab6ea-9907-434b-a4c4-ae4ba94eabb2'),
		# Tag(name='xss', category='url_pattern', match='http://testphp.vulnweb.com/hpp/params.php?p=valid&pp=12', extra_data={'source': 'url'}, _source='gf', _type='tag', _uuid='bbdcce78-c36a-43ef-8e34-f6e628455c6a'),
	],
	'host': [
		Port(port=3000, host='localhost', ip='127.0.0.1', state='open', _type='port'),
		Port(port=8080, host='localhost', ip='127.0.0.1', state='open', _type='port'),
		# Tag(name='FingerprintHub Technology Fingerprint - qm-system', match='http://localhost:3000', category='tech', extra_data={'data': []}, _source='nuclei'),
		# Tag(name='Public Swagger API - Detect', match='http://localhost:3000/api-docs/swagger.json', category='exposure', extra_data={'data': []}, _source='nuclei'),
		Vulnerability(
			matched_at='http://localhost:3000/metrics',
			ip='127.0.0.1',
			name='Prometheus Metrics - Detect',
			provider='',
			id='',
			confidence='high',
			severity='medium',
			cvss_score=5.3,
			confidence_nb=1,
			severity_nb=2,
			_type='vulnerability',
		),
		Vulnerability(
			matched_at='http://localhost:8080/',
			ip='127.0.0.1',
			name='Spring Boot - Remote Code Execution (Apache Log4j)',
			provider='',
			id='cve-2021-44228',
			confidence='high',
			severity='critical',
			cvss_score=10,
			confidence_nb=1,
			severity_nb=0,
			_type='vulnerability',
		),
		Url(url='http://localhost:3000', method='GET', _type='url'),
		Url(url='http://localhost:8080', method='GET', _type='url'),
		Url(url='http://localhost:3000/main.js', method='GET', _type='url'),
		Url(url='http://localhost:3000/runtime.js', method='GET', _type='url'),
		Url(url='http://localhost:8080', method='GET', _type='url'),
		Url(url='http://localhost:3000/polyfills.js', method='GET', _type='url'),
		Url(url='http://localhost:3000/vendor.js', method='GET', _type='url'),
		Url(url='http://localhost:3000/styles.css', method='GET', _type='url'),
		Url(url='http://localhost:3000/sitemap.xml', method='GET', _type='url'),
		Url(url='http://localhost:3000', method='GET', _type='url'),
		Url(url='http://localhost:3000/assets/public/favicon_js.ico', method='GET', _type='url'),
		Url(url='http://localhost:3000/robots.txt', method='GET', _type='url'),
	],
	'network': [],
	'url': [],
}
