name: domain
description: Default domain scan (subdomain_recon, host_recon, url_crawler)
profile: default
workflows:
  subdomain_recon:
  host_recon:
    targets_:
    - target.name
    - subdomain.host
  url_crawler:
    targets_:
    - url.url