name: network
description: Internal network scan (cidr_recon, url_crawler)
profile: default
workflows:
  cidr_recon:
  url_crawl:
    targets_:
    - type: ip
      field: ip
      condition: item.alive
  url_vuln:
    targets_:
    - url.url