type: scan
name: domain
description: Default domain scan (subdomain_recon, host_recon, url_crawl)
profile: default
workflows:
  subdomain_recon:
  host_recon:
    targets_:
    - target.name
    - subdomain.host
  url_crawl:
    targets_:
    - url.url
  url_vuln:
    targets_:
    - url.url