type: scan
name: network
description: Internal network scan
profile: default
input_types:
  - cidr_range
workflows:
  cidr_recon:
  url_nuclei:
    targets_:
    - url.url
  url_crawl:
    targets_:
    - url.url
  url_vuln:
    targets_:
    - url.url