# Default values for Secator
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

secatorManager:
  name: secator-manager
  image: "freelabz/secator"

  # resources: cpu/memory requests and limits for managers
  resources: {}

  # Empty if using default repository
  repository:
  # Empty if using tag "latest"
  tag:

secatorWorker:
  name: secator-worker
  image: "freelabz/secator"

  # resources: cpu/memory requests and limits for workers
  resources: {}
  replicas: 1

  # Empty if using default repository
  repository:
  # Empty if using tag "latest"
  tag:

redis:
  name: redis
  image: "redis:alpine"
  # resources: cpu/memory requests and limits for redis
  resources: {}

  # Empty if using default repository
  repository:
  # Empty if using tag "latest"
  tag:
  replicas: 1
  port: 6379
