type: workflow
name: host_recon
alias: hostrec
description: Run vulnerability scan on network and HTTP services
tags: [subdomain, url, vulnerability]
tasks:
  _group:
    naabu:
      description: Find open ports
    nuclei:
      description: Scan network and SSL vulnerabilities
      tags: [network, ssl]
  nmap:
    description: Search for vulnerabilities on open ports
    targets_: port.host
    ports_: port.port
  httpx:
    description: Prob HTTP services on open ports
    targets_:
      - type: port
        field: '{host}:{port}'
        condition: item._source == 'nmap'
  nuclei:
    description: Search for vulnerabilities on alive HTTP services
    exclude_tags: [network, ssl, file, dns, osint, token-spray, headers]
    targets_:
      - type: url
        field: url
        condition: item.status_code != 0
results:
  - type: port
    condition: item._source == 'nmap'

  - type: vulnerability
    condition: item.confidence == 'high'

  - type: url
    condition: item.status_code != 0