type: workflow
name: subdomain_recon
alias: subrec
description: Find subdomains and takeovers
tags: [subdomain, url, vulnerability, tech, subdomain_takeover]
tasks:
  subfinder:
    description: Listing subdomains (passive)
  # TODO: add subdomain bruteforcers
  # gobuster:
  #   input: vhost
  #   domain_:
  #     - target.name
  #   wordlist: /usr/share/seclists/Discovery/DNS/combined_subdomains.txt
  # gobuster:
  #   input: dns
  #   domain_:
  #     - target.name
  #   wordlist: /usr/share/seclists/Discovery/DNS/combined_subdomains.txt
  _group:
    nuclei:
      description: Checking for subdomain takeovers
      targets_:
      - target.name
      - subdomain.host
      tags: [takeover, dns]
    httpx:
      description: Running HTTP probes on subdomain root hosts
      targets_:
      - target.name
      - subdomain.host