type: workflow
name: url_fuzz
alias: urlfuzz
description: Find URLs by fuzz (slow)
tags: [http, fuzz]
options:
  match_codes: 200,204,301,302,307,401,403,405,500
tasks:
  _group:
    dirsearch:
      description: Fuzz URLs
    feroxbuster:
      description: Fuzz URLs
    ffuf:
      description: Fuzz URLs
      targets_:
        - type: target
          field: '{name}/FUZZ'
  httpx:
    description: Run HTTP probes on crawled URLs
    targets_:
      type: url
      field: url
results:
  - type: url
    condition: item._source == 'httpx'
    # TODO: add deduplication based on the 'url' field