type: workflow
name: url_nuclei
alias: url_nuclei
description: Search for URL vulnerabilities using Nuclei
tags: [http, vulnerability, nuclei]
tasks:
  nuclei:
    description: Searching for HTTP vulns
    exclude_tags: [network, ssl, file, dns, osint, token-spray, headers]