type: workflow
name: url_nuclei
alias: url_nuclei
description: Search for URL vulnerabilities us Nuclei
tags: [http, vulnerability, nuclei]
tasks:
  nuclei:
    description: Search for HTTP vulns
    exclude_tags: [network, ssl, file, dns, osint, token-spray, headers]