type: workflow
name: wordpress
alias: wordpress
description: Wordpress vulnerability scan
tags: [http, wordpress, vulnerability]
input_types:
  - url
tasks:
  _group:
    nuclei:
      description: Nuclei Wordpress scan
      tags: wordpress
    wpscan:
      description: WPScan