apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secator-worker.yaml
  - secator-manager.yaml
  - redis.yaml
  - redis-svc.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize