apiVersion: apps/v1
kind: Deployment
metadata:
  name: secator-worker
  namespace: secator
spec:
  selector:
    matchLabels:
      app: secator-worker
  template:
    metadata:
      labels:
        app: secator-worker
    spec:
      containers:
      - name: secator-worker
        image: freelabz/secator
        command: ["secator"]
        args: ["worker"]
        env:
        - name: SECATOR_CELERY_BROKER_URL
          value: "redis://redis:6379/0"
        - name: SECATOR_CELERY_RESULT_BACKEND
          value: "redis://redis:6379/0"