name: docker

on:
  push:
    branches:
    - release-please*
  pull_request:
    types: [labeled, synchronize]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  platform:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ci-docker')) }}
    strategy:
      fail-fast: false
      matrix:
        distribution: ["alpine", "arch", "debian", "kali", "osx", "ubuntu"]
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: "docker build -t freelabz/secator:${{ matrix.distribution }} -f .docker/Dockerfile.${{ matrix.distribution }} ."

    - name: Run secator health check (strict)
      run: docker run --privileged freelabz/secator:${{ matrix.distribution }} health --strict

    - name: Run Docker image ls to view size
      run: docker image ls
