name: release-test

on:
  push:
    branches:
      - release-please*

permissions:
  contents: write
  pull-requests: write

jobs:
  test-docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install secator
      uses: ./.github/actions/install
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: secator u build docker

    - name: Run secator health check (strict)
      run: docker run --privileged freelabz/secator:dev health --strict
